GreaterComponent support for multiple signals within a timeframe
FakeFishGames/Barotrauma pull request #11303
Opened 2023-02-21 10:13 UTC by mygamingaccount

This change would allow us to make simple circuits that compare multiple signals to see if any of them is greater or less than one, or many, signals.

It is a 100% backwards compatible way of allowing players to use Min(a,b) and Max(a,b) when comparing values.

Original description:
  Sends a signal if the value the signal_in1 input is larger than the signal_in2 input.

New description
  Sends a signal if a signal sent to signal_in1 input is larger than a signal sent to signal_in2 input within the timeframe.

Example: the circuit which compares if any of the devices need servicing.
Before:
![image](https://user-images.githubusercontent.com/68995233/220315937-e9d32db3-9d7d-4a9e-a628-556edc2b04d0.png)

After:
![image](https://user-images.githubusercontent.com/68995233/220314595-c1f55d24-5f2a-4fd2-8edd-739373dab426.png)

2023-12-07 21:38 UTC, Saevon commented
This would nicely let "greater than" support both MIN and MAX. Now if only we had a good guide that reminds you how to make common simple logic/math circuits using this system (in-game)

2024-10-22 13:30 UTC, Regalis11 requested changes
Thank you for the PR, and sorry for taking so long to take a look at this! I think this would be an useful change, but to me it seems like there's a handful of issues here - most importantly, I think this'd cause backwards compatibility issues because it changes the behavior of greater components in existing circuits too.

2024-10-22 13:30 UTC, Regalis11 commented on Barotrauma/BarotraumaShared/SharedSource/Items/Components/Signal/GreaterComponent.cs
> +        private float val2 = float.PositiveInfinity;
In my opinion the use of these sentinel values isn't the clearest way to go about this. I think it'd make the intention clearer if these were for example nullable floats, where null represents "no value received".

2024-10-22 13:30 UTC, Regalis11 commented on Barotrauma/BarotraumaShared/SharedSource/Items/Components/Signal/GreaterComponent.cs
> +                val2 = float.PositiveInfinity;
As far as I can see, this breaks backwards compatibility. It means the component will not keep sending the same output, but reverts back to false immediately after it's sent one output.

2024-10-22 13:30 UTC, Regalis11 commented on Barotrauma/BarotraumaShared/SharedSource/Items/Components/Signal/GreaterComponent.cs
> +                    val2 = signal2 < val2 ? signal2 : val2;
I believe this breaks backwards compatibility too. Previously the last received value was used, now the min/max value is used.

2025-01-10 13:23 UTC, Regalis11 commented
Does not seem to be in a mergeable state, closing at least for now

2025-01-10 13:23 UTC, closed without merging