Grenades rework
FakeFishGames/Barotrauma pull request #12522
Opened 2023-08-18 19:54 UTC by PanmanS

Anyways, here's what changes include:
- new sounds (made from game sounds)
- new pin pulling mechanic (press E) and cooking of grenades
- new effects on for EMP and STUN grenades
- new DoT effect for incendium grenade

XML file fully documented by original author (M12) with all changes highlighted
video demo of grenades:

[demo](https://youtu.be/4Uk3-7W8lIM)

![preimg](https://github.com/Regalis11/Barotrauma/assets/42521948/bcede48d-0931-43ec-a923-4493f180b7e1)
![preimg1](https://github.com/Regalis11/Barotrauma/assets/42521948/a2c729d3-5029-4742-a34d-2d1b58af1f03)
![preimg2](https://github.com/Regalis11/Barotrauma/assets/42521948/88cb1a7a-61bd-48ac-b167-677b9d347529)
![preimg3](https://github.com/Regalis11/Barotrauma/assets/42521948/4291a7c5-4830-4c82-80cc-fc75435e107a)
![preimg4](https://github.com/Regalis11/Barotrauma/assets/42521948/a3a108f1-1299-46ab-8560-dc0558d0c973)

2023-09-03 13:58 UTC, Regalis11 commented
Thank you for the PR!

I think we need to put some though on whether we'd like these changes to be included in the vanilla game. It's not entirely clear to me what the reasoning behind all of these changes and their gameplay implications are - for example, how are the incendium grenade changes intended to change the use of the grenades? What's the intention behind draining batteries? I'm having a hard time thinking of a situation where that'd be useful - I could imagine it being more of a nuisance if you had to go through all battery-powered tools/weapons and recharge them when a grenade goes off near a cabinet.

I also have some doubts about the new stun grenade effects. While I get the intention, I could imagine it not being very fun to have to stare at an empty screen, doing nothing, when you get hit by one: currently you can at least see what's happening (and what whoever threw you with the grenade is doing!).

I think there are also some clear issues here that need to be addressed if we decide to implement these changes: the biggest one is that the way the grenades are used doesn't seem to be communicated to the player in any way. I doubt I would myself figure out how they work, since E is never used for interacting with the equipped item anywhere else in the game. There's also the problem that you may end up accidentally triggering the grenades if you use E for something else with a grenade in your hand.

There's also some minor issues with the textures here: the pin texture is excessively large and poor quality and there's a very clear seam at the bottom of the blindoverlay texture. The smaller sprites should also be added into existing atlases for performance reasons, instead of creating completely new textures.

2023-09-04 07:31 UTC, PanmanS commented
Incedium grenade rework was made to make em usable in submarines, cause in current iteration they are way too destructive, causing more issues than good.

As for EMP grenades, that's exactly what they designed to do! Assuming you using it against bandits/pirates/wrecks/outposts and not against your own team.

Communication issue is big and we currently working on solution, since I doubt players will look at item description to know how to use it. (Although this issue is similiar to issue of handcuffs since, ironically, many players didnt figure out how to use before and that's probably why you guys added warning sign to prevent accidental cuffings)

As for textures issues - got it and we gonna try to mend em to fit the game

As for why we didnt include em into already existing atlases - we done for ease of inspection!

I will give you more detailed response when I will be home. Thank you for checking it out and pointing out issues!

2023-09-04 09:35 UTC, PanmanS commented
Thank you for your reply!

To get it out of the way from the start, yes, some sprites and overlays are crude and served more like a proof of concept, to give an idea on how it would look like in game. We are looking for making better sprites and further refining effects if their concept gets accepted. Their only purpose was to visualize the basic ideas behind changes.

Incendium grenades are in a weird spot in the game's balance. They are crafted from expensive and rare Incendium, which has far better use in nukes and fuel tanks, yet have less damage and range than frag grenades, that are crafted with UEX, which is available for purchase from the start and is extremely easy to produce. What makes them even worse - they cause fires that are a headache to deal with, dealing tones of collateral damage.  Even if your goal is to set something on fire, to cheese an outpost, for example, you'd be better off using molotovs(which become broadly available at approximately same time as incendium does), so incendium grenades are completely outclassed in every aspect.  I understand that they are meant to be volatile and dangerous to use onboard, but this just discourages players from using them at all since their effect against underwater targets and ballast flora(which is strange, since flora is usually killed with tool involving high temperatures) is greatly inferior to that of frag grenades.

Our changes to Incendium grenades aim to completely overhaul them, giving them a role as a sort of area-denial damage-over-time weapon, that players are encouraged to use indoors. they also now deal a bit more direct damage and a lot more ballast flora damage, giving them another niche use case as an effective, but expensive safety net against flora.

EMP grenades are probably the least generally useful and the most niche grenades out of all with their only real purpose in campaign being cheesing guardians. They are also sometimes used to disable supercapacitors in PvP(on azimuth and dugong its quit easy to do). Our changes aim on making them even more useful in PvP scenario(and also countering griefing, i know you like it). The best, most deadly and effective weapon there is The Stun Baton, powered by batteries. With this change EMP grenades now become a direct counter to one of the deadliest strategies in PvP, when in comes to human-to-human fight - camping in a crampt space with a stun baton. This now allows you to drain batteries of a baton abuser through walls or doors with no need to step in his effective range. Same applies to underwater scooters, that are, on the other hand, one of the few effective counters to melee in the game, and they are also powered by batteries.  (Trust M12 on this one, he griefed and destroyed hundreds of servers abusing stun batons, they really need a counter)

Stun grenades dont really need any tweaking in terms of their utility, they are already powerful enough to be consistently viable, though their visual and audio effects seem lacking to us. We added blindness and hearing distortion effects to disorient players hit by one, which is the main purpose of real stun grenades and also might provide possibility for some cheeky outplays in PvP scenarios.
The blindness is separated into two effects "Hard" one and a normal one. Hard Blindness doesnt allow player to see anything for 5 seconds, but only occurs in the epicenter of the blast. Normal blindness obstructs vision only partially, depending on how close to the explosion afflicted player was. Same goes for tinnitus and hearing distortion. 

We will continue our work on this branch, addressing issues you have pointed out. Communication problem can be solved by implementing a sort of a pop-up hint(like those that we already have in the game), or by editing their description. 
Hope that our explanation sheds some more light on the purposes of this overhaul and why we think its pretty important for the game.

2023-09-06 19:05 UTC, PanmanS commented
New version up

2023-09-15 18:55 UTC, PanmanS commented
We understand that it might be difficult to get all players to know about new feature at once, but we do think its possible to solve this communication issue.
First of all, if you decide to add this feature to the game it should be listed in the patch notes, preferably one of the first lines in the list. Introducing it first to unstable and only then to release version might also help as unstable testers would be the first to know about pins and will spread the information across community. We also can make a short demonstration video to showcase this feature.

Interface changes.
Use button in settings can be renamed to Use/Pull the pin. 
Popup hint - a new hint regarding grenades can be introduced, appearing once the player grabs any sort of grenade from a locker.  If it is possible, a forced(appears regardless of blocked popups setting) popup tip can be applied if the player threw grenade with its lightcomponent turned off (aka with safety in place)


There is also another variant. We may remake the grenades, adding pins but not removing their initial exploding logic. This way the grenade will go off normally with delay, like they do now in vanilla even if the pin wasn't pulled manually. However the option of prematurely removing the safety would still remain, allowing players to cook grenades before throwing. So now if player doesnt know how to pull the pin it would happen automatically as he throws the grenade. R.I.P. pranking potential on this one

Let us know which option is more preferable, if it is the second one, then we will soon release another request with that change implemented.

![image](https://github.com/Regalis11/Barotrauma/assets/42521948/af2154c6-ba83-491b-a399-a2e03101760a)
![image](https://github.com/Regalis11/Barotrauma/assets/42521948/c7fca33b-3918-4a5f-8040-dc655172a075)

2023-09-18 07:33 UTC, Regalis11 commented
One thing we're a bit hesitant about is that the new pin mechanic makes using the grenades slightly more unintuitive, since it's different from how you use any other item in the game, and different from how grenades work in most other games. It _can_ be communicated using in-game hints, but we're a little wary of introducing inconsistencies like this for what is quite a niche feature.

It can of course be explained in hints and such, but the way I see it, if something as simple as how to use a grenade needs a big info box to explain, that suggests it might not be as intuitive as it should be. And patch notes, mentioning the changes in Discord or videos are of course useful, but we cannot rely on information outside the game to communicate mechanics to the player. Not everyone reads the patch notes or follows Barotrauma content online.

2023-09-18 11:14 UTC, PanmanS commented
Consider taking a look through pre-last paragraph for variant that will satisfy both parties

2023-09-30 21:48 UTC, PanmanS commented
:pog:

2023-10-26 09:32 UTC, JeroonBosch commented
> Let us know which option is more preferable, if it is the second one, then we will soon release another request with that change implemented.

I think the latter (the hint) is preferable

2023-11-07 05:17 UTC, PanmanS commented
Adjusted per request

2023-11-20 13:23 UTC, Regalis11 requested changes
Thanks for the revision! Found a handful of issues here still. The others are mainly just small stylistic things we can address ourselves, but the "proxyincendium" item could use some clarification. Why's it needed, couldn't the incendium grenade spawn the emitters by itself?

2023-11-21 15:36 UTC, PanmanS commented on grenades.xml
> +    <Item name="proxyincendium" identifier="incendium_proxy" category="Weapon" maxstacksize="32" maxstacksizecharacterinventory="8" cargocontaineridentifier="explosivecrate" tags="smallitem" hideinme
There's a little issue we have.
We cant get the incendium emitters to always shoot upward regardless of grenade's position consistently without a static proxy item. 
Fixed RotationType doesn't seem to work, we are out of ideas. M12 tried asking modders in undertow discord but neither they knew a way. If there is a way to do it, we dont know it so we ask for your help to give us a hint on what attributes we should be using for this logic to work properly.

2023-11-21 15:47 UTC, Regalis11 commented on grenades.xml
> +    <Item name="proxyincendium" identifier="incendium_proxy" category="Weapon" maxstacksize="32" maxstacksizecharacterinventory="8" cargocontaineridentifier="explosivecrate" tags="smallitem" hideinme
How/why doesn't it work? If it's bugged somehow, that's something we need to fix rather than using a hacky workaround like the proxy item.

2023-11-21 19:03 UTC, PanmanS commented on grenades.xml
> +    <Item name="proxyincendium" identifier="incendium_proxy" category="Weapon" maxstacksize="32" maxstacksizecharacterinventory="8" cargocontaineridentifier="explosivecrate" tags="smallitem" hideinme
We tried putting Rotationtype on fixed and Aimspread 0 with Fixedspread true + Rotation 90

Upon tossing nade up and making it explode mid-air - Most explosions shoot the emitter to the left and sometimes to right

Meanwhile when I place the grenade into 4 detonators, each rotated 0, 90, 180 and 270 degrees - Every single one shoots the emmiter upwards
 
 When grenade thrown on floor - Most of the times it fires downwards and sometimes fires to the right.
 
 So in the end Ive been throwing these grenades for like half an hour tweaking the rotation value.
It just gets randomly flipped sometimes.

2023-11-22 05:47 UTC, PanmanS commented on grenades.xml
> +    <Item name="proxyincendium" identifier="incendium_proxy" category="Weapon" maxstacksize="32" maxstacksizecharacterinventory="8" cargocontaineridentifier="explosivecrate" tags="smallitem" hideinme
Update: we managed to find a bypass without emitter, but fixed rotation type still didnt work as expected for us. Await new version of pr with all mistakes corrected in 11 hours from this message.

2023-11-22 14:00 UTC, PanmanS commented
As you requested, we further refined our code, addressing issues you've pointed out.  Formatting has been changed and is now consistent throughout all of the code, typos were fixed and identifiers of particles refined. We also cleared some issues with tags and fabrication recipes that slipped past us before.
Incendium grenade and it's emitters were changed to make their behavior more consistent, proxy item was removed as well. (huuuge thanks to Uberpendragon)
We also got rid of the "bg_" prefix on afflictions, since that meant "Better Grenades" and was a leftover from m12's mod we used as a base for this request. 


We changed the comments to make them more clear, adding proper punctuation and removing the unneeded ones. Though it  should be noted, that we didn't expect any of the comments to make it to an actual game build since they were written simply to give you or any other possible viewer a clear understanding of the idea behind rework without a need to test it in game.
We also left the names of afflictions unchanged, since they are hidden in-game(cannot be seen by inspection or HUDs), and we've seen hardcoded names on those hidden afflictions in vanilla (Slow for example).

2023-12-27 18:49 UTC, PanmanS commented
Ayo happy new year in advance

2024-01-04 11:56 UTC, PanmanS commented
We would be glad but we dont know hoe to make our own custom hints

2024-03-04 22:16 UTC, PanmanS commented
Guh?

2024-03-05 10:04 UTC, JeroonBosch requested changes
The actual added/modified text lines in EnglishVanilla.xml should ideally be in a clean empty XML file (EnglishVanillaNew.xml)

2024-03-05 12:33 UTC, PanmanS commented
Got it

2024-03-05 12:34 UTC, JeroonBosch commented
No need to change it atm as I've manually copied it already (I believe it was just one hint added?) but for future PRs!

2024-03-05 12:39 UTC, PanmanS commented
Noted, thank you!

2024-03-05 20:49 UTC, PanmanS commented
Note: Will update chem nade tommorow with what i think is better version, originaly made by uber!

2024-03-06 08:54 UTC, zhu-rengong commented
Is it possible to consider adding the process of holding the striker lever? I think this would make grenade play more fun.

I made a quick video to show 4 ways to trigger grenade:
1. Click 'E' and throw (Normalest way)
2. Click 'E' firstly to pull the pin, and then continue to click 'E' again to release the spoon
3. Click 'E' and the grenade will start cooking when the holder is knocked down
4. Click 'E' and the grenade will start cooking when it's not on holding

https://github.com/FakeFishGames/Barotrauma/assets/73634685/0097c492-4845-455f-a47e-e44f8de772bf
https://github.com/FakeFishGames/Barotrauma/assets/73634685/2d5935ff-d104-4792-8bf4-5aaf2e46ab9a

Of course, it still can be triggered instanly by detonator(fifth way) but just not being demonstrated in the video.

I have played it with my friends for nearly half a year and have not found any bugs yet. If you want to consider it, you can check the folloing code (related mod: OTFX):
```xml
<Item name="" identifier="otfx_jcoffdef1fraggrenade" category="Weapon" tags="smallitem,weapon,explosive,demolitionsexpert" maxstacksize="32" maxstacksizecharacterinventory="8" scale="0.4" cargocontaineridentifier="explosivecrate" impactsoundtag="impact_metal_heavy">
  <InventoryIcon texture="%ModDir%/OTFX/Items/InventoryIconAtlas.png" sourcerect="320,320,64,64" origin="0.5,0.5" />
  <Sprite texture="%ModDir%/OTFX/Items/Weapons/weapons.png" sourcerect="640,512,46,89" depth="0.55" origin="0.5,0.65" />
  <BrokenSprite texture="%ModDir%/OTFX/Items/Weapons/weapons.png" sourcerect="704,512,46,89" depth="0.55" origin="0.5,0.65" maxcondition="99.9" />
  <BrokenSprite texture="%ModDir%/OTFX/Items/Weapons/weapons.png" sourcerect="768,512,46,89" depth="0.55" origin="0.5,0.65" maxcondition="99.8" />
  <Body width="40" height="70" density="30" />
  <Throwable slots="Any,RightHand,LeftHand" holdpos="0,0" handle1="0,0" throwforce="3.5" msg="ItemMsgPickUpSelect">
    <!-- Based on the code here: https://github.com/FakeFishGames/Barotrauma/blob/0c433eb187b20f4bd24a1919b478529b387ee0bf/Barotrauma/BarotraumaShared/SharedSource/Items/Components/ItemComponent.cs#L925-L935 -->
    <!-- We used the following four StatusEffects to track the user who throw the grenade, pull the pin and release the spoon -->
    <StatusEffect type="OnSecondaryUse" target="This" indestructible="true" condition="0.0" setvalue="true">
      <Conditional condition="lte 99.9" />
    </StatusEffect>
    <StatusEffect type="OnSecondaryUse" target="This" indestructible="false" setvalue="true" />
    <StatusEffect type="OnUse" target="This" indestructible="true" condition="0.0" setvalue="true" comparison="And">
      <Conditional condition="gte 99.9" hasstatustag="! unusable" />
    </StatusEffect>
    <StatusEffect type="OnUse" target="This" indestructible="false" setvalue="true" />

    <StatusEffect type="OnUse" target="This" condition="99.8" setvalue="true" comparison="And">
      <Conditional condition="99.9" />
      <Conditional hasstatustag="! unusable" />
    </StatusEffect>
    <StatusEffect type="OnUse" target="This" targetitemcomponent="Powered" condition="99.9" isactive="true" setvalue="true" comparison="And">
      <Conditional isfullcondition="true" />
      <Conditional hasstatustag="! unusable" />
    </StatusEffect>
    <StatusEffect type="OnUse" target="This" tags="unusable" duration=".033" stackable="false" />
    <StatusEffect type="OnActive" target="This" tags="onholding" duration=".033" stackable="false" />
  </Throwable>
  <Powered characterusable="false">
    <StatusEffect type="OnUse" target="This" condition="0.0" setvalue="true" />
    <StatusEffect type="OnBroken" target="This">
      <Sound file="Content/Items/Weapons/ExplosionMedium1.ogg" range="5000" frequency="2.0" selectionmode="Random" />
      <Sound file="Content/Items/Weapons/ExplosionMedium2.ogg" range="5000" frequency="2.0" />
      <Sound file="Content/Items/Weapons/ExplosionMedium3.ogg" range="5000" frequency="2.0" />
      <ParticleEmitter particle="shrapnel" anglemin="0" anglemax="360" distancemax="500" particleamount="270" velocitymin="1500" velocitymax="2000" scalemin="0.7" scalemax="1.2" />
      <Explosion range="600.0" ballastfloradamage="100" structuredamage="20" levelwalldamage="140" itemdamage="350" force="5" debris="false" decal="explosion" decalsize="0.5">
        <Affliction identifier="explosiondamage" strength="150" />
        <Affliction identifier="stun" strength="4.0" />
      </Explosion>
      <Explosion range="500.0" itemdamage="50" force="3" severlimbsprobability="0.5" sparks="false" shockwave="false" flames="false" underwaterbubble="false" smoke="false" playtinnitus="false" flash="false" camerashake="5">
        <Affliction identifier="gunshotwound" probability="0.3" strength="10" dividebylimbcount="false" />
        <Affliction identifier="bleeding" probability="0.3" strength="10" dividebylimbcount="false" />
        <Affliction identifier="stun" strength="0.5" />
      </Explosion>
      <Explosion range="900.0" itemdamage="50" force="3" severlimbsprobability="0.5" sparks="false" shockwave="false" flames="false" underwaterbubble="false" smoke="false" playtinnitus="false" flash="false" camerashake="4">
        <Affliction identifier="gunshotwound" probability="0.3" strength="15" dividebylimbcount="false" />
        <Affliction identifier="bleeding" probability="0.3" strength="15" dividebylimbcount="false" />
        <Affliction identifier="stun" strength="0.5" />
      </Explosion>
      <Explosion range="1300.0" itemdamage="50" force="3" severlimbsprobability="0.5" sparks="false" shockwave="false" flames="false" underwaterbubble="false" smoke="false" playtinnitus="false" flash="false" camerashake="3">
        <Affliction identifier="gunshotwound" probability="0.3" strength="20" dividebylimbcount="false" />
        <Affliction identifier="bleeding" probability="0.3" strength="20" dividebylimbcount="false" />
        <Affliction identifier="stun" strength="0.5" />
      </Explosion>
      <Remove />
    </StatusEffect>

    <StatusEffect type="OnActive" target="This" targetitemcomponent="Powered" isactive="false" setvalue="true">
      <Conditional lastconditionchange="gt 0.0" />
    </StatusEffect>
    <StatusEffect type="OnActive" target="This" condition="99.8" setvalue="true" comparison="And">
      <Conditional condition="99.9" />
      <Conditional hasstatustag="! onholding" />
    </StatusEffect>
    <StatusEffect type="OnActive" target="This" condition="99.8" setvalue="true" comparison="And">
      <Conditional condition="99.9" />
      <Conditional targetcontainer="true" entitytype="Character" isknockeddown="true" />
    </StatusEffect>
    <!-- Fuse time: 5s -->
    <StatusEffect type="OnActive" target="This" condition="-19.96">
      <Conditional condition="lte 99.8" />
    </StatusEffect>
    <StatusEffect type="OnActive" target="This" comparison="And">
      <Sound file="%ModDir%\OTFX\Items\Weapons\grenade_pinpull1.ogg" range="500" selectionmode="Random" />
      <Sound file="%ModDir%\OTFX\Items\Weapons\grenade_pinpull2.ogg" range="500" />
      <ParticleEmitter particle="otfx_jcoffdef1fraggrenadesafetypin" particleamount="1" copyentityangle="true" anglemin="70" anglemax="100" velocitymin="100" velocitymax="200" />
      <Conditional condition="lte 99.9" />
      <Conditional hasstatustag="! pinpulled" />
    </StatusEffect>
    <StatusEffect type="OnActive" target="This" tags="pinpulled" duration=".05" stackable="false">
      <Conditional condition="lte 99.9" />
    </StatusEffect>
    <StatusEffect type="OnActive" target="This" comparison="And">
      <Sound file="%ModDir%\OTFX\Items\Weapons\grenade_strikerlever1.ogg" range="500" selectionmode="Random" />
      <Sound file="%ModDir%\OTFX\Items\Weapons\grenade_strikerlever2.ogg" range="500" />
      <ParticleEmitter particle="otfx_jcoffdef1fraggrenadespoon" particleamount="1" copyentityangle="true" anglemin="-60" anglemax="-30" velocitymin="100" velocitymax="200" />
      <Conditiona [...]

2024-03-06 20:48 UTC, PanmanS commented
I dont think I wanna implement strike system either. As for fixes, postponed to next day, sorry guys!

2024-03-07 05:11 UTC, zhu-rengong commented
I checked File Changes, and I seem to understand that Pull Pin is an optional mechanism. I seem to ignore this.
Although the Strike system can also be made into options, it undoubtedly increases complexity.

2024-03-07 15:19 UTC, PanmanS commented
As you requested, we fixed stun grenade's overlay texture alongside some other minor inconsistencies including files now actually having a proper vanilla code structure.

We also tweaked acid grenade a bit, shortening its fuse time and delay before it starts spawning emitters. We also fixed its behaviour in detonators. 
As a bonus, we also decided to improve audio and visuals of incendium and stun grenades. Incendium emitters now use FireSmall.ogg as their active sound and produce a small flickering light source, as fire should. As for the stun grenades, we added screen distortion and improved on other effects to make them seem more realistic.


As for the interactions with other items, we think that a bit of a change to the fire extinguisher could be applied. If this pr gets accepted and we end up with incendiary grenades that ignite creatures and leave burning puddles, then it would make sense for the fire extinguisher to become a countermeasure to that. As for now, these puddles are extinguished instantly if they come in contact with water (same goes for the burning affliction), but we also think it would be great for players to have an ability to put out these fires and help their burning teammates by using the extinguisher.  Let us know if you would agree of that, and if that's the case, we would update our pr to feature the extinguisher changes!

2024-03-07 15:20 UTC, PanmanS reviewed
Should be fixed now.

2024-03-08 11:36 UTC, Regalis11 commented
Oh, we didn't intend to request any changes, as @JeroonBosch said we've already copied this to a PR in our private repo. I guess we'll need to do that again then. I'll close the PR now, so we have to re-re-re-re-review any new changes. :D Thank you for your contribution!

2024-03-08 11:36 UTC, closed without merging

2024-03-08 11:37 UTC, JeroonBosch requested changes
> - shortened fuse of acid grenade
> - incendium emitters now use FireSmall.ogg as their active sound and produce a small flickering light source
> - stun grenade now has additional screen distortion
> - fixed annoying seam on blindedoverlay.png
> - EnglishVanilla.xml now contains only new text
> - all files represent Unstable V1.2.13.0 version

Doing this all in the same commit when I already manually copied things before creates a huge hassle, we were under the impression this PR was supposed to be done? Perhaps you can separate things like "all files represent Unstable V1.2.13.0 version" which causes 6000 of lines changed in Afflictions.xml from things like "stun grenade now has additional screen distortion" in separate commits so we can in the commit what actually changed.

2024-03-08 11:44 UTC, Regalis11 commented
^ Agreed.
![image](https://github.com/FakeFishGames/Barotrauma/assets/14351070/6639a0ed-6a1b-4cfa-86f9-451413e89cf9)

It's impossible for us to see what was actually changed here, and we're not going to start reviewing 12,299 lines of code changes.

2024-03-08 15:57 UTC, PanmanS commented
sorreh about that... Sob.

2024-03-08 20:04 UTC, Regalis11 commented
No worries! I think we can probably still move the latest commits to our private repo and compare the difference to the v1.2.13.0 version, it would've just been more convenient to be able to see the the changes in the commit.

2024-03-11 15:31 UTC, JeroonBosch commented
Feel free to paste snippets of XML for the following fixes here, btw:

> - shortened fuse of acid grenade
> - incendium emitters now use FireSmall.ogg as their active sound and produce a small flickering light source
> - stun grenade now has additional screen distortion
> - fixed annoying seam on blindedoverlay.png