Moping jack retexture
FakeFishGames/Barotrauma pull request #14010
Opened 2024-05-25 23:39 UTC by EebleSheembl

Makes Moping Jack not just a bigger Hammerhead by giving it a custom sprite and ragdoll

2024-05-25 23:53 UTC, EebleSheembl commented
![image](https://github.com/FakeFishGames/Barotrauma/assets/152429881/7febbda5-0338-47a6-a100-c6ce05d7eb0b)

2024-09-14 09:46 UTC, Regalis11 requested changes
I feel the texture needs some more work. There's some strange blurry spots around the edges and the top fins. The texture also has a ton of unnecessary empty space.

2024-09-14 18:45 UTC, EebleSheembl commented
This was mainly a recolor of the normal hammerhead sprite with some damage added to it which would mean that those would probably be problems on the normal one too, though I might remake it as I was new to this whole thing and I could make it better now

2024-09-14 19:42 UTC, EebleSheembl commented
![image](https://github.com/user-attachments/assets/ebfd94db-321e-435e-9ab4-9c2813feddc8)

2024-09-15 20:40 UTC, ubertpendragon commented
> The texture also has a ton of unnecessary empty space.

I agree, there's empty space in the texture 😉 
![image](https://github.com/user-attachments/assets/7f8466f6-c802-44b7-bc4c-a2c3cf976978)

2024-09-15 21:24 UTC, EebleSheembl commented
Yeah there's that one the normal hammerhead sprite, fixed it with this sprite though

2024-09-16 06:48 UTC, Regalis11 requested changes
> This was mainly a recolor of the normal hammerhead sprite with some damage added to it which would mean that those would probably be problems on the normal one too

Just because there's issues in an existing texture doesn't mean we should add more with similar issues, especially when they'd be trivial to address. The texture still consists of mostly empty space, there's no reason to make it 1024px1024x when it would easily fit in half of that.

2024-09-16 07:44 UTC, EebleSheembl commented
Reduced the empty space

2025-01-05 20:20 UTC, 711885 commented
The changes that were requested were made, so is this considered? You should probably resolve the conversation/close the review

2025-01-10 13:31 UTC, Regalis11 commented
Sorry for taking so long to get back to this! This looks good to me now with the latest changes, merged to our private repo. Thank you for your contribution!

2025-01-10 13:31 UTC, closed without merging