Fix custom sprite deformation not mirroring when character flips
FakeFishGames/Barotrauma pull request #15456
Opened 2024-12-30 17:51 UTC by TheNinjaScout

Adds "isFlipped" parameter to all "GetDeformation" methods, only used in "CustomDeformation" for now to read the deformation rows in an inverse order when the character is flipped

Fixes https://github.com/FakeFishGames/Barotrauma/discussions/15434

https://github.com/user-attachments/assets/cc04ced6-b605-4693-b7a7-662ad6b39cf5

2025-01-07 14:24 UTC, Regalis11 requested changes
I think there are a couple of issues here, see comments

2025-01-07 14:24 UTC, Regalis11 commented on Barotrauma/BarotraumaClient/ClientSource/Sprite/DeformAnimations/CustomDeformation.cs
> +        protected override void GetDeformation(out Vector2[,] deformation, out float multiplier, bool inverse, bool isFlipped = false)
The difference between `inverse` and `isFlipped` seems unclear to me.

2025-01-07 14:24 UTC, Regalis11 commented on Barotrauma/BarotraumaClient/ClientSource/Sprite/DeformAnimations/CustomDeformation.cs
> +                Vector2[,] flippedDeformation = new Vector2[Deformation.GetLength(0), Deformation.GetLength(1)];
This causes a new array to be initialized every time the method is called. That's not good for performance: the flipped array should be cached and reused (perhaps it could be created in the constructor already).

2025-01-07 14:24 UTC, Regalis11 commented on Barotrauma/BarotraumaClient/ClientSource/Sprite/DeformAnimations/CustomDeformation.cs
> +                int height = Deformation.GetLength(1);
Would make sense to store the width and height before creating the array and reuse the values, instead of getting the lengths twice.

2025-01-08 23:28 UTC, TheNinjaScout commented on Barotrauma/BarotraumaClient/ClientSource/Sprite/DeformAnimations/CustomDeformation.cs
> +        protected override void GetDeformation(out Vector2[,] deformation, out float multiplier, bool inverse, bool isFlipped = false)
Inverse seems to only ever be used by customdeformation even though it's defined as a parameter for all deformations,

https://github.com/FakeFishGames/Barotrauma/blob/38ca721cb0fd94aadbb9c1886ba2338bbd5f1180/Barotrauma/BarotraumaClient/ClientSource/Sprite/DeformAnimations/CustomDeformation.cs#L112-L119

https://github.com/FakeFishGames/Barotrauma/blob/38ca721cb0fd94aadbb9c1886ba2338bbd5f1180/Barotrauma/BarotraumaClient/ClientSource/Sprite/DeformAnimations/SpriteDeformation.cs#L225-L233

 **and** it's only ever set to true when getting the deformation for deformable light sprites and not normal ones, 
https://github.com/FakeFishGames/Barotrauma/blob/38ca721cb0fd94aadbb9c1886ba2338bbd5f1180/Barotrauma/BarotraumaClient/ClientSource/Characters/Limb.cs#L831

after some testing I found out that deformable light sprites with custom deformation actually appear to deform correctly when the character is flipped in the current public build of the game, 


https://github.com/user-attachments/assets/6c40decc-44ba-441e-bf55-d0b3536599b6



If we set inverse to true for normal deformable sprites
https://github.com/FakeFishGames/Barotrauma/blob/38ca721cb0fd94aadbb9c1886ba2338bbd5f1180/Barotrauma/BarotraumaClient/ClientSource/Characters/Limb.cs#L827

like it is being done for light deformable sprites based on the direction of the character results in this happening, 


https://github.com/user-attachments/assets/c1062e27-f6da-4bca-b804-bb8bd0fee242


so I'm assuming inverse was made as a solution for light deformable sprites, but not normal deformable ones?

2025-01-09 00:03 UTC, TheNinjaScout commented
The custom deformation behaves a bit differently when comparing a non flipped limb to a flipped limb, not sure if it's a problem with my fix implementation or something else:

https://github.com/user-attachments/assets/c41702f6-6f49-428d-a9ba-d598b9e4db51

2025-01-15 11:32 UTC, Regalis11 commented
Thanks for the clarification! I'm still a bit unhappy about `inverse` and `isFlipped`, it's not at all obvious how they differ - but I couldn't quite figure out either why `inverse` works the way it does and why it should be used. Moved this to a PR in our private repo (https://github.com/FakeFishGames/Barotrauma-development/pull/6231) with some additional comments on those.

2025-01-15 11:32 UTC, closed without merging